#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch_music.xyz"
EWW="$HOME/.local/bin/eww -c $HOME/.config/eww/widgets"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
    ${EWW} daemon
    sleep 1
fi

## Open widgets 
run_eww() {
    ${EWW} open music
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
    touch "$FILE"
    run_eww
else
    ${EWW} close music
    rm "$FILE"
fi

