#!/usr/bin/env bash

FILE="$HOME/.cache/eww_launch_widgets.xyz"
EWW="eww -c $HOME/.config/eww/widgets/"

if [[ ! `pidof eww` ]]; then
    ${EWW} daemon
    sleep 1
fi

run_eww() {
    ${EWW} open date
    ${EWW} open poweroff
    ${EWW} open res
    ${EWW} open quit
    ${EWW} open time
}

if [[ ! -f "$FILE" ]]; then
    touch "$FILE"
    run_eww
else
    ${EWW} close date
    ${EWW} close poweroff
    ${EWW} close res
    ${EWW} close quit
    ${EWW} close time
    rm "$FILE"
fi
