#!/bin/bash

bspc monitor -d 1 2 3 4 5 6
bspc config border_width         0
bspc config window_gap           16
bspc config split_ratio          0.6
bspc config normal_border_color "#dadada"
bspc config focused_border_color "#dadada"
bspc config presel_feedback_color "#dadada"
bspc config top_padding 42
bspc config left_padding 0

$HOME/.config/bspwm/scripts/start.sh
