#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5 6
bspc config border_width         2
bspc config window_gap           16
bspc config split_ratio          0.6
bspc config focused_border_color "#1b1f20"
bspc config presel_feedback_color "#d8b4bd"
bspc config top_padding 40
bspc config -m HDMI-0 left_padding 40
bspc config -m HDMI-0 top_padding 0

~/.config/bspwm/scripts/start.sh