#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5 6
bspc config border_width         2
bspc config window_gap           16
bspc config split_ratio          0.6
bspc config normal_border_color "#0d1117"
bspc config focused_border_color "#0d1117"
config presel_feedback_color "#0d1117"
pkill borders ; borders &
bspc config top_padding 45
bspc config left_padding 50
bspc config top_padding 0
~/.config/bspwm/scripts/start.sh
